# Generated by Django 4.2 on 2024-11-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0004_alter_meeting_status_meetingextensionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('extended', 'Extended'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], max_length=20)),
                ('original_times', models.JSONField()),
                ('new_times', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='meetings.meeting')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MeetingExtensionHistory',
        ),
    ]
